
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GruziVezi
{

using System;
    using System.Collections.Generic;
    
public partial class Cars
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cars()
    {

        this.Drivers = new HashSet<Drivers>();

    }


    public int id { get; set; }

    public string number { get; set; }

    public int id_ModelCar { get; set; }



    public virtual ModelCars ModelCars { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Drivers> Drivers { get; set; }

}

}
