

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GruziVezi
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class GruziVeziEntities : DbContext
{
    public GruziVeziEntities()
        : base("name=GruziVeziEntities")
    {

    }
        private static GruziVeziEntities _context;
        public static GruziVeziEntities GetContext()
        {
            if (_context == null)
                _context = new GruziVeziEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cars> Cars { get; set; }

    public virtual DbSet<Cities> Cities { get; set; }

    public virtual DbSet<Company> Company { get; set; }

    public virtual DbSet<Drivers> Drivers { get; set; }

    public virtual DbSet<ModelCars> ModelCars { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Routes> Routes { get; set; }

    public virtual DbSet<Senders> Senders { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

