
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GruziVezi
{

using System;
    using System.Collections.Generic;
    
public partial class Orders
{

    public int id { get; set; }

    public int id_Sender { get; set; }

    public int id_Driver { get; set; }

    public int id_Route { get; set; }

    public string description { get; set; }

    public int id_Status { get; set; }

    public int id_User { get; set; }



    public virtual Drivers Drivers { get; set; }

    public virtual Routes Routes { get; set; }

    public virtual Senders Senders { get; set; }

    public virtual Status Status { get; set; }

    public virtual Users Users { get; set; }

}

}
